name: main
on: push

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
    - name: Check out the main branch
      uses: actions/checkout@v1
      with:
        ref: master
    - name: Capture the screenshot
      env:
        DISPLAY: ':0.0'
      run: |
        set -x
        # Configure Git for the push from the workflow to the repository
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config --global user.name "github-actions[bot]"
        # Install Node dependencies
        npm install
        # Start XVFB so that Electron can start and then have a screenshot taken
        /usr/bin/Xvfb :0 &
        # Run the test which generates the screenshot
        npm start
        # Stage the captured screenshot
        git add screenshot-*.png
        # Reset unstaged changes so that Git commit won't fail (e.g.: package-lock.json, temporary files, …)
        git checkout -- .
        git commit -m "Commit the captured screenshot"
        # Pull before pushing to integrate fast forward changes if any
        git pull --rebase
        # Push the generated data to GitHub
        git push
